### ISSUE TITLE
Unable to compile "modules/ppocr/src/ppocr/box_char/box.cpp"

### ISSUE THREAD

**Issue by dtouzeau** [wallix/redemption#13]
Hi,

Try to install redemption on debian 9 but have some issue after bjam command.

    /redemption# bjam toolset=gcc
    error: Unable to find file or target named
    error:     'modules/ppocr/src/ppocr/box_char/box.cpp'
    error: referred to from project at
    error:     '.'

**Comment by dtouzeau** [comment]
Fixed : 

missed run 

    git submodule update --init

**Comment by FrankyBoy** [comment]
Problem persists in the release packages. Idk if that is a github or project issue though.

**Comment by jonathanpoelen** [comment]
When you download the source, either via tags or the button on the project page, github doesn't integrate the sub-modules, since they're not really part of the project source (this is git-related information). You have to retrieve the sub-modules linked to the version yourself. As everything on redemption is located in a modules folder, the link is `https://github.com/wallix/redemption/tree/${TAG}/modules`  (for example, 10.5.25 for ${TAG}).

The latest versions don't have this problem, as there are no longer any sub-modules.
