### ISSUE TITLE
Outgoing TLS level not configurable by default

### ISSUE THREAD

**Issue by jclc** [wallix/redemption#167]
I need to limit the outgoing TLS versions for RDP connections via `mod_rdp->tls_{min,max}_level` but the config setting is not being recognised by default due to `no_ini_no_gui` in config_spec.hpp. Is there a good reason for this and if not, would you accept a pull request changing this to something else (eg. `advanced_in_gui`)?

**Comment by jonathanpoelen** [comment]
The 2 variables also have the `*connpolicy` attribute, which means they are configurable via acl. You can do this by adding `kv['mod_rdp:tls_min_level'] = value` to your version of passthrough.py.

Since you're talking about `no_ini_no_gui`, this corresponds to maintenance branches. We won't accept a PR on this modification because it will have an impact on our environment (connpolicy option and incompatible with ini option).

But we're in the process of making changes to the future branch and the `connpolicy` is also configurable from the ini file. You can still use the latest version, but some options have changed name or value and you'll have to use `tools/conf_migration_tool/conf_migrate.py` to update your configuration.
