### ISSUE TITLE
enable Video recording

### ISSUE THREAD

**Issue by hadadiashkan** [wallix/redemption#31]
How is it possible to record video without realizing the user?
setting output format!
setting output directory and ....
It seems that video tests are failed.

**Comment by jonathanpoelen** [comment]
1. What do you mean by that? If nothing is done in `passthrough.py`, there is no message saying that a recording is being made.
2. That is not possible. Instead, enable the `wrm` recording in `capture_flag` of the ini file and use `redrec` to generate a video. `redrec -f --video-codec mp4 -o path.mp4 .....` works, but there is no guarantee for other formats. It is also necessary that `passthrough.py` send `is_rec=1` otherwise there will be no capture. 
3. Only at compilation time: [Setting build variables](https://github.com/wallix/redemption#setting-build-variables). Don't forget `bjam -a ....` to recompile everything.
4. The tests compare the size of the videos which is very dependent on the version of ffmpeg and codecs. We think comparisons with a margin of error, but nothing is done for now because "it works here"…

**Comment by hadadiashkan** [comment]
The problem is that with this method you can not see the video in real-time.

**Comment by jonathanpoelen** [comment]
That's right..... After checking, there is a `codec_id` option in the `globals` section of the ini file, but I don't know which format will work properly. For historical reasons, several `video` and `mod_rdp` options are in `globals`.

For "real time" other than video, `passthrough.py` can send `rt_display=1`. This will create png images in the temporary recording folder.

**Comment by hadadiashkan** [comment]
thank you. i'll try that too.
