### ISSUE TITLE
Too large video mp4 size

### ISSUE THREAD

**Issue by tahmoor** [wallix/redemption#50]
When setting **codec_id=mp4**, recorded mp4 files are too large. It seems that Redemption does not compress mp4 files. How is it possible to set compression parameters, such as CRF, for mp4 recording?

**Comment by jonathanpoelen** [comment]
This is not possible at the moment. The video options will soon be redesigned to allow a custom option list to be sent to the video codec.

In recent days, there have been some changes on the ffmpeg API used with a small improvement on the weight of video files.

**Comment by jonathanpoelen** [comment]
There is now an option `ffmpeg_options` in section `[video]`. Or `--video-codec-options` with `redrec`. The default value is `profile=baseline preset=ultrafast flags=+qscale b=30000`.

This replaces the old values: `video_quality`, `{l,m,h}_bitrate` `{l,m,h}_framerate` and `{l,m,h}_qscale`.

/!\ The options must be valid for the codec used, otherwise the video recording will fail.

**Comment by firesasin** [comment]
profile=baseline preset=ultrafast flags=+qscale b=30000
> preset option
I found out these options : ultrafast, fast

What are the other options?
